### ISSUE TITLE
Motion of hair components

### ISSUE THREAD

**Issue by banhuML** [mmmmmm44/VTuber-Python-Unity#11]
Hello, thanks for your work, that's very interesting. I like it so I tried the live2d part. But when I follow the steps, when I shake my head, the part of the character's hair doesn't seem to move slightly as shown. How should I set it? Thank You!

**Comment by mmmmmm44** [comment]
When running in Unity Editor, the hair animation cannot render that well. But if you build the project (i.e. create an .exe in windows/ an application in mac), you will get the smooth hair animation as shown in the README.

**Comment by banhuML** [comment]
Thanks for your reply！It worked！
