### ISSUE TITLE
Error, Can you help me?

### ISSUE THREAD

**Issue by ersanliqiao** [mmmmmm44/VTuber-Python-Unity#2]
NullReferenceException: Object reference not set to an instance of an object
UnityChanController.Start () (at Assets/Scripts/UnityChanController.cs:66)

The code is: 

        GameObject.FindWithTag("GameController").GetComponent<UISystem>().LoadData();
        GameObject.FindWithTag("GameController").GetComponent<UISystem>().InitUI();

**Comment by mmmmmm44** [comment]
Please download the sample unity project in the UnityAssets/Packages and import them to a blank project, and observe how do I set up the UI and other stuff

Of course you can uncomment these two lines and other part related to the UI and save load system and the project still can be run.

**Comment by ersanliqiao** [comment]
OK，thank you, I will try.

**Comment by Ryan-zyy** [comment]
> Please download the sample unity project in the UnityAssets/Packages and import them to a blank project, and observe how do I set up the UI and other stuff
> 
> Of course you can comment these two lines and other part related to the UI and save load system and the project still can be run.

I got the same problem, and i try to set unitychan's tag to be GameController, but it didn't work.

can u help me plz? thanks :)

![image](https://user-images.githubusercontent.com/50386590/145387958-a07c3c58-ea2f-4d68-a0c9-26eae4f9694d.png)

**Comment by Ryan-zyy** [comment]
> Please download the sample unity project in the UnityAssets/Packages and import them to a blank project, and observe how do I set up the UI and other stuff
> 
> Of course you can comment these two lines and other part related to the UI and save load system and the project still can be run.

I got the same problem, and i try to set unitychan's tag to be GameController, but it didn't work.

can u help me plz? thanks :)

![image](https://user-images.githubusercontent.com/50386590/145387958-a07c3c58-ea2f-4d68-a0c9-26eae4f9694d.png)

**Comment by mmmmmm44** [comment]
Please clone the project and check out the sample project for 3D unity chan

In the image below, notice the hierarchy tree, there is an object called App Controller, which is responsible for the UI stuff. And the tag is exactly "GameController".
![image](https://user-images.githubusercontent.com/40860474/145572686-d15919dc-2c53-42df-93aa-8cabbe7adf20.png)

Alternatively, please disable line 66 and 67 of UnityChanController.cs, which are the two lines responsible for running functions in the script UISystem.cs attached to it. These two lines are responsible for loading user preferences (for detection) and load the UI components. Then the program should run smoothly.

**Comment by RyanProMax** [comment]
> Please clone the project and check out the sample project for 3D unity chan by importing the package.
> 
> In the image below, notice the hierarchy tree, there is an object called App Controller, which is responsible for the UI stuff. And the tag is exactly "GameController". ![image](https://user-images.githubusercontent.com/40860474/145572686-d15919dc-2c53-42df-93aa-8cabbe7adf20.png)
> 
> Alternatively, please disable line 66 and 67 of UnityChanController.cs, which are the two lines responsible for running functions in the script UISystem.cs attached to it. These two lines are responsible for loading user preferences (for detection) and load the UI components. Then the program should run smoothly.

thank u very much, i will try it again!

**Comment by Andy-Lyu** [comment]
I‘m also confused about how to run Unity sucessfully. Acoording your image,I set as the same,but the result is not teh same. whether I  have set canvas somthing [error.](https://github.com/Andy-Lyu/Audy_Rep/blob/master/1.png)

**Comment by Andy-Lyu** [comment]
[img](https://github.com/Andy-Lyu/Audy_Rep/blob/master/1.png)

**Comment by Andy-Lyu** [comment]
I‘m also confused about how to run Unity sucessfully. Acoording your image,I set as the same,but the result is not teh same. whether I have set canvas somthing error.
![1](https://user-images.githubusercontent.com/56439647/147199930-15359743-ab11-46b9-90ae-0ebc0fa155d5.png)

**Comment by mmmmmm44** [comment]
Please watch the video walkthrough prepared in youtube:

https://youtu.be/V6Wd2kPNbPY?t=180

Follow the instructions mentioned in the video and the descriptions if any error is faced.

Alternatively, you may download the unity package of the sample project.
Link: https://www.dropbox.com/sh/qh7dcqt0z287idt/AACbljJEcD6knM6JL2uojfIaa?dl=0

**Comment by Andy-Lyu** [comment]
thanks，it's very kind of you.  Do you use bilibili? I think you can be a good uploader.

**Comment by mmmmmm44** [comment]
No, I don't use bilibili.

However, you can share the youtube video and this project to your friends who wish to try playing around with such technology. I will be very grateful.

Happy coding and experimenting.
