### ISSUE TITLE
import error, how to resolve?

### ISSUE THREAD

**Issue by jinfagang** [mmmmmm44/VTuber-Python-Unity#6]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/21303438/158067969-67f3ad3e-1770-4504-8c5f-1a2fa515aafa.png">

**Comment by mmmmmm44** [comment]
Are you having another C# script which is named UnityChanController.cs in another folder?

Delete the one which you think is redundant.

If you cannot decide which one, create a new project and import the corresponding unitypackage (UnityChan one) into the new project.

Hopefully this can solve your problem.

**Comment by jinfagang** [comment]
@mmmmmm44 I found there are 2 sets of cs scripts, one is from your GitHub, another one is imported from unity.package, they are almost same, but not fully same, what's the differences?

**Comment by mmmmmm44** [comment]
U can use diff <file1> <file2> command in linux/mac or fc <file1> <file2> on windows to compare them.

They are the same files (i.e. no difference)
